### ISSUE TITLE
Setup Logging on Web API project

### ISSUE THREAD

**Issue by oleh-leobit** [adrnchk/DogeNet#26]
Investigate possible ways of logging and implement one

**Comment by adrnchk** [comment]
@oleh-leobit can I use NLog for it?

**Comment by oleh-leobit** [comment]
@adrnchk what about default ILogger? You are free to choose what you prefer. Please, leave a comment on which package you will use and why.

**Comment by adrnchk** [comment]
Ok, I will use NLog cause it is very comfortable, flexible, free logging platform with ability to write multiple targets at once (console and file), also it supports .net 6.
