### ISSUE TITLE
Setup authorization

### ISSUE THREAD

**Issue by oleh-leobit** [adrnchk/DogeNet#28]
Configure Identity Server to add authorization to the project

**Comment by adrnchk** [comment]
@oleh-leobit 
The fact is that when I add the mediator in the API with the assembly BLL
![image](https://user-images.githubusercontent.com/77879337/165493884-61a6f82d-b03d-4210-a240-e45f5e88cd8b.png)
, it requires CreateAccountCommand, which uses UserManager service,
![image](https://user-images.githubusercontent.com/77879337/165494452-a0a52bef-cea8-4717-bd25-8c2fd822a4df.png)
 and if I register the service, it will require identity, 
![image](https://user-images.githubusercontent.com/77879337/165494862-717aab2f-62df-4b72-99c7-5ce851e5da2e.png)
and identity redirects to api/Account/Login which is 404
