### ISSUE TITLE
Add code analyzers

### ISSUE THREAD

**Issue by oleh-leobit** [adrnchk/DogeNet#3]
There are some models on the DAL level that contains empty lines. To avoid any code style issues we need to add code analyzers to the projects.

**Comment by adrnchk** [comment]
Whish one code analizer should I add? Is this smth like pretier extention for VS?

**Comment by adrnchk** [comment]
@oleh-leobit 
Smth like that?
![image](https://user-images.githubusercontent.com/77879337/139259905-4bd22bba-d297-45ce-a6cb-4427531fb85c.png)

**Comment by adrnchk** [comment]
I have added StyleCop analizer. It gave me a lot of warnings I already solved (exept elements documentation - set them to silent mode)

**Comment by oleh-leobit** [comment]
@adrnchk 

Good for you!
