### ISSUE TITLE
Setup authorization

### ISSUE THREAD

**Issue by oleh-leobit** [adrnchk/DogeNet#5]
In the scope of this ticket, you should investigate possibilities of setting up authorization for web applications, choose the best variant for our case and implement one. For testing purposes, you could create one endpoint (any which would require auth in your application).

So acceptance criteria:
- investigate auth implementations 
- choose and implement one
- create an endpoint that will return some data from the DB and will require authorization

**Comment by adrnchk** [comment]
I supose that the best authentication method for social networks is JWT authentification. The token will be generated once and with no expire date (or very long), than it would be stored in cookies (or maybe in local sorage).

**Comment by adrnchk** [comment]
@oleh-leobit 
What do you think about that?

**Comment by oleh-leobit** [comment]
@adrnchk 

JWT is OK for our case, but I don't like tokens without expiration.

**Comment by oleh-leobit** [comment]
@adrnchk 

What about Identity Server? Do you find something related to that?

**Comment by adrnchk** [comment]
IdentityServer is an OpenID Connect provider - it implements the OpenID Connect and OAuth 2.0 protocols. It can centralize authentification service to avoid repeating same auth. feature in different APIs.

**Comment by adrnchk** [comment]
I think it is great idea to learn and use that lib. Cause I think I'll certainly bump into it in nearest future.
