### ISSUE TITLE
Document README file

### ISSUE THREAD

**Issue by oleh-leobit** [adrnchk/DogeNet#8]
In the scope of this ticket, you should update the readme file with information that would be useful during installation (some npm commands for installing packages on UI, or some tech requirements of this project). Also, it should include some short descriptions of the project and main funcitons.

**Comment by oleh-leobit** [comment]
@adrnchk 

I saw you started working with it yesterday. 
Does it really take more than one day of implementing?

**Comment by adrnchk** [comment]
It is already done, but should I create new branch for this issue or just push it to develop?

**Comment by adrnchk** [comment]
@oleh-leobit 
I decided to commit it to develop branch
